
# Gem::Specification for Hobo-0.8.5
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: hobo
version: !ruby/object:Gem::Version 
  version: 0.8.5
platform: ruby
authors: 
- Tom Locke
autorequire: 
bindir: bin

date: 2008-12-09 00:00:00 +00:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: hobosupport
  type: :runtime
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - "="
      - !ruby/object:Gem::Version 
        version: 0.8.5
    version: 
- !ruby/object:Gem::Dependency 
  name: hobofields
  type: :runtime
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - "="
      - !ruby/object:Gem::Version 
        version: 0.8.5
    version: 
- !ruby/object:Gem::Dependency 
  name: rails
  type: :runtime
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: 2.2.2
    version: 
- !ruby/object:Gem::Dependency 
  name: mislav-will_paginate
  type: :runtime
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: 2.2.1
    version: 
description: The web app builder for Rails
email: tom@tomlocke.com
executables: 
- hobo
extensions: []

extra_rdoc_files: 
- bin/hobo
- lib/action_view_extensions/helpers/tag_helper.rb
- lib/active_record/association_collection.rb
- lib/active_record/association_proxy.rb
- lib/active_record/association_reflection.rb
- lib/extensions/test_case.rb
- lib/hobo/accessible_associations.rb
- lib/hobo/authentication_support.rb
- lib/hobo/bundle.rb
- lib/hobo/composite_model.rb
- lib/hobo/controller.rb
- lib/hobo/dev_controller.rb
- lib/hobo/dryml/dryml_builder.rb
- lib/hobo/dryml/dryml_doc.rb
- lib/hobo/dryml/dryml_generator.rb
- lib/hobo/dryml/dryml_support_controller.rb
- lib/hobo/dryml/parser/attribute.rb
- lib/hobo/dryml/parser/base_parser.rb
- lib/hobo/dryml/parser/document.rb
- lib/hobo/dryml/parser/element.rb
- lib/hobo/dryml/parser/elements.rb
- lib/hobo/dryml/parser/source.rb
- lib/hobo/dryml/parser/text.rb
- lib/hobo/dryml/parser/tree_parser.rb
- lib/hobo/dryml/parser.rb
- lib/hobo/dryml/part_context.rb
- lib/hobo/dryml/scoped_variables.rb
- lib/hobo/dryml/tag_parameters.rb
- lib/hobo/dryml/taglib.rb
- lib/hobo/dryml/template.rb
- lib/hobo/dryml/template_environment.rb
- lib/hobo/dryml/template_handler.rb
- lib/hobo/dryml.rb
- lib/hobo/find_for.rb
- lib/hobo/generator.rb
- lib/hobo/guest.rb
- lib/hobo/hobo_helper.rb
- lib/hobo/include_in_save.rb
- lib/hobo/lifecycles/actions.rb
- lib/hobo/lifecycles/creator.rb
- lib/hobo/lifecycles/lifecycle.rb
- lib/hobo/lifecycles/state.rb
- lib/hobo/lifecycles/transition.rb
- lib/hobo/lifecycles.rb
- lib/hobo/model.rb
- lib/hobo/model_controller.rb
- lib/hobo/model_router.rb
- lib/hobo/model_support.rb
- lib/hobo/permissions/associations.rb
- lib/hobo/permissions.rb
- lib/hobo/rapid_helper.rb
- lib/hobo/scopes/apply_scopes.rb
- lib/hobo/scopes/association_proxy_extensions.rb
- lib/hobo/scopes/automatic_scopes.rb
- lib/hobo/scopes/named_scope_extensions.rb
- lib/hobo/scopes.rb
- lib/hobo/static_tags
- lib/hobo/undefined.rb
- lib/hobo/undefined_access_error.rb
- lib/hobo/user.rb
- lib/hobo/user_controller.rb
- lib/hobo/view_hints.rb
- lib/hobo.rb
- LICENSE.txt
- README
- tasks/environments.rake
- tasks/fix_dryml.rake
- tasks/generate_tag_reference.rake
- tasks/hobo_tasks.rake
files: 
- bin/hobo
- CHANGES.txt
- dryml_generators/rapid/cards.dryml.erb
- dryml_generators/rapid/forms.dryml.erb
- dryml_generators/rapid/pages.dryml.erb
- init.rb
- lib/action_view_extensions/helpers/tag_helper.rb
- lib/active_record/association_collection.rb
- lib/active_record/association_proxy.rb
- lib/active_record/association_reflection.rb
- lib/extensions/test_case.rb
- lib/hobo/accessible_associations.rb
- lib/hobo/authentication_support.rb
- lib/hobo/bundle.rb
- lib/hobo/composite_model.rb
- lib/hobo/controller.rb
- lib/hobo/dev_controller.rb
- lib/hobo/dryml/dryml_builder.rb
- lib/hobo/dryml/dryml_doc.rb
- lib/hobo/dryml/dryml_generator.rb
- lib/hobo/dryml/dryml_support_controller.rb
- lib/hobo/dryml/parser/attribute.rb
- lib/hobo/dryml/parser/base_parser.rb
- lib/hobo/dryml/parser/document.rb
- lib/hobo/dryml/parser/element.rb
- lib/hobo/dryml/parser/elements.rb
- lib/hobo/dryml/parser/source.rb
- lib/hobo/dryml/parser/text.rb
- lib/hobo/dryml/parser/tree_parser.rb
- lib/hobo/dryml/parser.rb
- lib/hobo/dryml/part_context.rb
- lib/hobo/dryml/scoped_variables.rb
- lib/hobo/dryml/tag_parameters.rb
- lib/hobo/dryml/taglib.rb
- lib/hobo/dryml/template.rb
- lib/hobo/dryml/template_environment.rb
- lib/hobo/dryml/template_handler.rb
- lib/hobo/dryml.rb
- lib/hobo/find_for.rb
- lib/hobo/generator.rb
- lib/hobo/guest.rb
- lib/hobo/hobo_helper.rb
- lib/hobo/include_in_save.rb
- lib/hobo/lifecycles/actions.rb
- lib/hobo/lifecycles/creator.rb
- lib/hobo/lifecycles/lifecycle.rb
- lib/hobo/lifecycles/state.rb
- lib/hobo/lifecycles/transition.rb
- lib/hobo/lifecycles.rb
- lib/hobo/model.rb
- lib/hobo/model_controller.rb
- lib/hobo/model_router.rb
- lib/hobo/model_support.rb
- lib/hobo/permissions/associations.rb
- lib/hobo/permissions.rb
- lib/hobo/rapid_helper.rb
- lib/hobo/scopes/apply_scopes.rb
- lib/hobo/scopes/association_proxy_extensions.rb
- lib/hobo/scopes/automatic_scopes.rb
- lib/hobo/scopes/named_scope_extensions.rb
- lib/hobo/scopes.rb
- lib/hobo/static_tags
- lib/hobo/undefined.rb
- lib/hobo/undefined_access_error.rb
- lib/hobo/user.rb
- lib/hobo/user_controller.rb
- lib/hobo/view_hints.rb
- lib/hobo.rb
- LICENSE.txt
- Manifest
- rails_generators/hobo/hobo_generator.rb
- rails_generators/hobo/templates/application.css
- rails_generators/hobo/templates/application.dryml
- rails_generators/hobo/templates/dryml-support.js
- rails_generators/hobo/templates/guest.rb
- rails_generators/hobo/templates/initializer.rb
- rails_generators/hobo_front_controller/hobo_front_controller_generator.rb
- rails_generators/hobo_front_controller/templates/controller.rb
- rails_generators/hobo_front_controller/templates/functional_test.rb
- rails_generators/hobo_front_controller/templates/helper.rb
- rails_generators/hobo_front_controller/templates/index.dryml
- rails_generators/hobo_front_controller/USAGE
- rails_generators/hobo_model/hobo_model_generator.rb
- rails_generators/hobo_model/templates/fixtures.yml
- rails_generators/hobo_model/templates/hints.rb
- rails_generators/hobo_model/templates/model.rb
- rails_generators/hobo_model/templates/unit_test.rb
- rails_generators/hobo_model/USAGE
- rails_generators/hobo_model_controller/hobo_model_controller_generator.rb
- rails_generators/hobo_model_controller/templates/controller.rb
- rails_generators/hobo_model_controller/templates/functional_test.rb
- rails_generators/hobo_model_controller/templates/helper.rb
- rails_generators/hobo_model_controller/USAGE
- rails_generators/hobo_model_resource/hobo_model_resource_generator.rb
- rails_generators/hobo_model_resource/templates/controller.rb
- rails_generators/hobo_model_resource/templates/functional_test.rb
- rails_generators/hobo_model_resource/templates/helper.rb
- rails_generators/hobo_rapid/hobo_rapid_generator.rb
- rails_generators/hobo_rapid/templates/blank.gif
- rails_generators/hobo_rapid/templates/hobo-rapid.css
- rails_generators/hobo_rapid/templates/hobo-rapid.js
- rails_generators/hobo_rapid/templates/IE7.js
- rails_generators/hobo_rapid/templates/lowpro.js
- rails_generators/hobo_rapid/templates/reset.css
- rails_generators/hobo_rapid/templates/themes/clean/public/images/fieldbg.gif
- rails_generators/hobo_rapid/templates/themes/clean/public/images/pencil.png
- rails_generators/hobo_rapid/templates/themes/clean/public/images/small_close.png
- rails_generators/hobo_rapid/templates/themes/clean/public/images/spinner.gif
- rails_generators/hobo_rapid/templates/themes/clean/public/stylesheets/clean.css
- rails_generators/hobo_rapid/templates/themes/clean/public/stylesheets/rapid-ui.css
- rails_generators/hobo_rapid/templates/themes/clean/views/clean.dryml
- rails_generators/hobo_subsite/hobo_subsite_generator.rb
- rails_generators/hobo_subsite/templates/application.dryml
- rails_generators/hobo_subsite/templates/controller.rb
- rails_generators/hobo_subsite/templates/site_taglib.dryml
- rails_generators/hobo_user_controller/hobo_user_controller_generator.rb
- rails_generators/hobo_user_controller/templates/controller.rb
- rails_generators/hobo_user_controller/templates/functional_test.rb
- rails_generators/hobo_user_controller/templates/helper.rb
- rails_generators/hobo_user_controller/USAGE
- rails_generators/hobo_user_model/hobo_user_model_generator.rb
- rails_generators/hobo_user_model/templates/fixtures.yml
- rails_generators/hobo_user_model/templates/forgot_password.erb
- rails_generators/hobo_user_model/templates/mailer.rb
- rails_generators/hobo_user_model/templates/model.rb
- rails_generators/hobo_user_model/templates/unit_test.rb
- rails_generators/hobo_user_model/USAGE
- Rakefile
- README
- script/destroy
- script/generate
- taglibs/core.dryml
- taglibs/rapid.dryml
- taglibs/rapid_core.dryml
- taglibs/rapid_document_tags.dryml
- taglibs/rapid_editing.dryml
- taglibs/rapid_forms.dryml
- taglibs/rapid_generics.dryml
- taglibs/rapid_lifecycles.dryml
- taglibs/rapid_navigation.dryml
- taglibs/rapid_pages.dryml
- taglibs/rapid_plus.dryml
- taglibs/rapid_support.dryml
- taglibs/rapid_user_pages.dryml
- tasks/environments.rake
- tasks/fix_dryml.rake
- tasks/generate_tag_reference.rake
- tasks/hobo_tasks.rake
- test/generators/test_generator_helper.rb
- test/generators/test_helper.rb
- test/generators/test_hobo_model_controller_generator.rb
- test/permissions/models/models.rb
- test/permissions/models/schema.rb
- test/permissions/models/test.sqlite3
- test/permissions/test_permissions.rb
- hobo.gemspec
has_rdoc: true
homepage: http://hobocentral.net/
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Hobo
- --main
- README
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: hobo
rubygems_version: 1.3.1
specification_version: 2
summary: The web app builder for Rails
test_files: 
- test/dryml/complilation_test.rb
- test/generators/test_generator_helper.rb
- test/generators/test_helper.rb
- test/generators/test_hobo_model_controller_generator.rb
- test/permissions/test_permissions.rb
